### ISSUE TITLE
No InterTechno dimming

### ISSUE THREAD

**Issue by GoogleCodeExporter** [curzon01/light-manager-c-ext#2]
```
Modern InterTechno devices supports dimming, but this program doesn't. I'm not 
a programmer and it took me a lot of effort to get this to work, so I can't be 
that much of an help.

Would it be possible to support (direct) dimming. From what I have found I 
think the signal should take just a couple of different bits.

Thanks for this fantastic program anyway!
```

Original issue reported on code.google.com by `j.boer...@gmail.com` on 25 Jun 2013 at 1:02

**Comment by Neuroplant** [comment]
Hello,
just see [https://github.com/curzon01/light-manager-c-ext/issues/7](url) how to fix dimming for Intertechno devices.
You are not limited to only  send 25, 50, 75 percent, while infact intertechno ony supports 16 dimming  stepps.
Neuroplant
